# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sathish Kumar
tagline:          'I am Sathish'
description:      'My Personal Blog'
url:              http://www.iamsais.com
baseurl:          /

author:
  name:           'Sathish'
  url:            https://twitter.com/iamsais
  email:		  sathish26586@gmail.com

twitter:
  url:		  https://twitter.com/iamsais

facebook:
  url:		  https://www.facebook.com/iamsais

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/iamsais/myblog-iamsais
