# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Sathish Kumar
tagline:          'I am Sathish'
description:      'My Personal Blog'
url:              http://www.iamsais.com
baseurl:          /

author:
  name:           'Sathish'
  url:            https://twitter.com/iamsais

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/iamsais/myblog-iamsais
